name: docker push

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set short SHA
        id: vars
        run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ashekun/python-app:${{ env.short_sha }}

  
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: login argocd
        uses: clowdhaus/argo-cd-action/@main
        with:
          version:  2.6.7
          command: login
          options:
              --username ${{ vars.ARGOCD_USERNAME }} \
              --password ${{ secrets.ARGOCD_PASSWORD }}
              --insecure \
              --grpc-web \
              argo-argocd-server.argo \ 
      - name: sync argocd
        uses: clowdhaus/argo-cd-action/@main 
        with:
          version: 2.6.7
          command: app sync
          options: python-app
